version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - run:
        name: Update yarn
        command: 'sudo npm install -g yarn@latest'
    - restore_cache:
        key: dependency-cache-{{ arch }}-{{ checksum "yarn.lock" }}
    - run:
        name: yarn
        command: yarn
    - save_cache:
        key: dependency-cache-{{ arch }}-{{ checksum "yarn.lock" }}
        paths:
        - node_modules
        - ~/.cache/yarn
    - run:
        command: yarn test -- --coverage --coveragePathIgnorePatterns=src/setupTests.js \
            --coveragePathIgnorePatterns=src/actions/testhelper.js
    - run:
        command: cat coverage/lcov.info | node_modules/.bin/coveralls
